name: string_calculator
description: A string calculator that adds numbers from a comma-separated string.
version: 1.0.0

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  test: ^1.24.0

dev_dependencies:
  lints: ^5.0.0

executables:
  string_calculator: string_calculator
